@endpoint = http://localhost:8088

@entity=message

### 查看所有meta entity patch配置
# GET {{endpoint}}/api/meta/patch/config/machines?whereFieldName={{entity}}
GET {{endpoint}}/api/meta/patch/config/machines


### 查看meta entity patch配置
GET {{endpoint}}/api/meta/patch/config/machines/{{entity}}


### 添加meta entity patch配置
POST {{endpoint}}/api/meta/patch/config/machines
Content-Type: application/json;charset=utf-8

{
  "entity": "device",
  "entityTableName": "nft_player",
  "entityFieldName": "delete_flag",
  "entityFieldType": "NUMBER",
  "whereFieldName": "player_id",
  "numberRangeMax": 1,
  "numberRangeMin": 1000,
  "permission": null
}


### 更新实体
@id=1

POST {{endpoint}}/api/meta/entity/{{entity}}/entities/{{id}}/action/update
Content-Type: application/json

{
  "reference_id": 2,
  "title": "test title"
}



### 更新实体（可指定实体ID字段）
@entityId=TASK

POST {{endpoint}}/api/meta/entity/{{entity}}/entities/{{entityId}}/action/update
Content-Type: application/json

{
  "value": "test"
}

#### 单条件查询
GET  {{endpoint}}/api/meta/entity/{entity}/onlyEntity/{condition}/action/select



### 逻辑删除实体
POST {{endpoint}}/api/meta/entity/{entity}/entities/{id}/action/logicDelete

### 恢复逻辑删除的实体
POST {{endpoint}}/api/meta/entity/{entity}/entities/{id}/action/logicDelete/recovery

### 批量逻辑删除的实体
POST {{endpoint}}/api/meta/entity/{entity}/entities/action/bulk/logicDelete

{
  "ids":
   [
    4,3
  ]
}

### 批量恢复逻辑删除的实体
POST {{endpoint}}/api/meta/entity/{entity}/entities/action/bulk/logicDelete/recovery

{
  "ids": [
    4,7
  ]
}

### 批量更新实体字段
POST {{endpoint}}/api/meta/entity/{entity}/entities/action/bulk/update

[
  {
    "id":4,
    "status":"test4",
    "device_id":"test_id"
  },
  {
    "id":7,
    "status":"test7",
    "device_id":"test_id"
  }

]

### 批量删除实体
POST {{endpoint}}/api/meta/entity/{entity}/entities/action/bulk/delete

{
  "ids": [
    4,7
  ]
}





###查询全部条件

GET  {{endpoint}}/api/meta/patch/config/whereFiled/device/select


#### 创建条件
#whereFieldName 需要添加条件字段名

POST {{endpoint}}/api/meta/patch/config/whereFiled/device/create

{
  "whereFieldName":"device_id"
}

#### 更新条件
#stusta row 删除整条记录  filed where只设置空
PUT  {{endpoint}}/api/meta/patch/config/whereFiled/device/update

{
  "oldWhereFieldName":"device_id",
  "newWhereFieldName":"device_id_test",
   "stusta":"row"
}

####删除条件
#stusta row 删除整条记录  filed where只设置空
POST {{endpoint}}/api/meta/patch/config/whereFiled/device/delete

{
  "whereFieldName":"device_id",
  "stusta":"row"
}
