@endpoint = http://localhost:8088

### 查看meta entity patch配置
POST {{endpoint}}/api/meta/patch/config/records/{entity}

### 添加meta entity patch配置
POST {{endpoint}}/api/meta/patch/config/records

{
  "entity": "string",
  "entityFieldName": "string",
  "entityFieldType": "string",
  "entityTableName": "string",
  "numberRangeMax": 0,
  "numberRangeMin": 0,
  "permission": "string"
}

### 更新实体
POST {{endpoint}}/api/meta/patch

### 下移实体排序
POST {{endpoint}}/api/meta/patch/entity/{entity}/action/movedown/row/{id}/row/{nextId}

### 上移实体排序
POST {{endpoint}}/api/meta/patch/entity/{entity}/action/moveup/row/{id}/row/{nextId}

### 批量逻辑删除的实体
POST {{endpoint}}/api/meta/patch/entity/{entity}/entities/action/bulk/logicDelete

{
  "ids":
   [
    0
  ]
}

### 批量恢复逻辑删除的实体
POST {{endpoint}}/api/meta/patch/entity/{entity}/entities/action/bulk/logicDelete/recovery

{
  "ids": [
    0
  ]
}

### 批量更新实体
POST {{endpoint}}/api/meta/patch/entity/1/entities/bulk

[
  {}
]

### 批量删除实体
POST {{endpoint}}/api/meta/patch/entity/{entity}/entities/bulk/delete

{
  "ids": [
    0
  ]
}

### 更新实体
POST {{endpoint}}/api/meta/patch/entity/1/entities/1

{}

### 逻辑删除实体
POST {{endpoint}}/api/meta/patch/entity/{entity}/entities/{id}/action/logicDelete

### 恢复逻辑删除的实体
POST /api/meta/patch/entity/{entity}/entities/{id}/action/logicDelete/recovery