@endpoint = http://localhost:8088

### 下移实体排序
POST {{endpoint}}/api/meta/entity/{entity}/action/movedown/row/2/row/1


### 上移实体排序
POST {{endpoint}}/api/meta/entity/{entity}/action/moveup/row/{id}/row/{nextId}
