@endpoint = http://localhost:8088

### 查看meta entity patch配置
GET {{endpoint}}/api/meta/patch/config/records/status

### 添加meta entity patch配置
POST {{endpoint}}/api/meta/patch/config/records

{
  "entity": "delete_flag",
  "entityFieldName": "delete_flag",
  "entityFieldType": "int",
  "entityTableName": "nft_player",
  "numberRangeMax": 1,
  "numberRangeMin": 1000,
  "permission": "null"
}

### 逻辑删除实体
POST {{endpoint}}/api/meta/patch/entity/delete_flag/entities/2/action/logicDelete

### 恢复逻辑删除的实体
POST {{endpoint}}/api/meta/patch/entity/delete_flag/entities/2/action/logicDelete/recovery


### 批量逻辑删除的实体
POST {{endpoint}}/api/meta/patch/entity/delete_flag/entities/action/bulk/logicDelete

{
  "ids":
   [
    1,2
  ]
}

### 批量恢复逻辑删除的实体
POST {{endpoint}}/api/meta/patch/entity/delete_flag/entities/action/bulk/logicDelete/recovery

{
  "ids": [
    1,2
  ]
}




### 以下测试不通过 pending todo
### 批量更新实体
POST {{endpoint}}/api/meta/patch/entity/1/entities/bulk

[
  {}
]

### 批量删除实体
POST {{endpoint}}/api/meta/patch/entity/{entity}/entities/bulk/delete

{
  "ids": [
    0
  ]
}

### 下移实体排序
POST {{endpoint}}/api/meta/patch/entity/nftPlayer/action/movedown/row/2/row/1

### 上移实体排序
POST {{endpoint}}/api/meta/patch/entity/{entity}/action/moveup/row/{id}/row/{nextId}

### 更新实体(没有返回操作)
POST {{endpoint}}/api/meta/patch/entity/name/entities/1

{
 
}

### 更新实体
POST {{endpoint}}/api/meta/patch/entity/1/entities/1

{}