###
@Endpoint = http://localhost:8088


### 获取meta配置列表
GET {{Endpoint}}/api/meta/change/setting


### 修改指定实体名的字段
PUT {{Endpoint}}/api/meta/change/testme/avatar?id=1
content-type: application/json

{
    "value":"[{value}]"
}


### 字段追加
POST {{Endpoint}}/api/meta/change/testme/avatar?id=1
content-type: application/json

{
    "value":"56456465645"
}



### 修改字段(数字类型)
PUT {{Endpoint}}/api/meta/change/testme/number?id=1
content-type: application/json

{
    "value": 1221
}


### 字段追加(数字类型)
POST {{Endpoint}}/api/meta/change/testme/number?id=2
content-type: application/json

{
    "value":121
}