version: "3"
services:
  mbcs:
    image: zelejs/allin-web:jdk11
    privileged: true
    container_name: mbcs
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./api:/webapps
    environment:
      DL_STANDALONE: "mbcs-1.1.0-standalone.jar"

networks:
  default:
    external:
      name: ${network}
