@endpoint=http://localhost:8080

### Generator Code within Path 生成单表代码并返回代码路径
POST {{endpoint}}/api/cg/generate/code HTTP/1.1
content-type: application/json

{
    "module": "apicode",
    "tableName":"lc_api_field_model",
    "fields": [
        {
            "fieldName": "template_name",
            "defaultValue":"",
            "isNotNull": 0,
            "isUnique": 0,
            "comments": "模板标识名称",
            "fieldType": "varchar",
            "fieldLength":26,
            "fieldFloatLength":0
        },
        {
            "fieldName": "template_label",
            "defaultValue":"",
            "isNotNull": 0,
            "isUnique": 0,
            "comments": "模板显示名称",
            "fieldType": "varchar",
            "fieldLength":26,
            "fieldFloatLength":0
        },
        {
            "fieldName": "default_value",
            "defaultValue":"",
            "isNotNull": 0,
            "isUnique": 0,
            "comments": "默认值",
            "fieldType": "varchar",
            "fieldLength":26,
            "fieldFloatLength":0
        },
        {
            "fieldName": "is_not_null",
            "defaultValue":"",
            "isNotNull": 1,
            "isUnique": 0,
            "comments": "是否非空",
            "fieldType": "smallint",
            "fieldLength":6,
            "fieldFloatLength":0
        },
        {
            "fieldName": "is_unique",
            "defaultValue":"",
            "isNotNull": 1,
            "isUnique": 0,
            "comments": "是否唯一",
            "fieldType": "smallint",
            "fieldLength":6,
            "fieldFloatLength":0
        },
        {
            "fieldName": "default_field_name",
            "defaultValue":"",
            "isNotNull": 0,
            "isUnique": 0,
            "comments": "推荐字段名称",
            "fieldType": "varchar",
            "fieldLength":26,
            "fieldFloatLength":0
        },
        {
            "fieldName": "optional_field_name",
            "defaultValue":"",
            "isNotNull": 0,
            "isUnique": 0,
            "comments": "可选的字段名称",
            "fieldType": "varchar",
            "fieldLength":26,
            "fieldFloatLength":0
        },
        {
            "fieldName": "field_type",
            "defaultValue":"",
            "isNotNull": 0,
            "isUnique": 0,
            "comments": "字段类型",
            "fieldType": "varchar",
            "fieldLength":26,
            "fieldFloatLength":0
        },
        {
            "fieldName": "field_length",
            "defaultValue":"",
            "isNotNull": 0,
            "isUnique": 0,
            "comments": "字段大小",
            "fieldType": "varchar",
            "fieldLength":26,
            "fieldFloatLength":0
        },
        {
            "fieldName": "field_float_length",
            "defaultValue":"",
            "isNotNull": 0,
            "isUnique": 0,
            "comments": "字段小数大小",
            "fieldType": "smallint",
            "fieldLength":6,
            "fieldFloatLength":0
        },
        {
            "fieldName": "comments",
            "defaultValue":"",
            "isNotNull": 0,
            "isUnique": 0,
            "comments": "注释",
            "fieldType": "varchar",
            "fieldLength":26,
            "fieldFloatLength":0
        }
    ]
}