@endpoint=http://localhost:8000

### Generator Code within Path 生成单表代码并返回代码路径
POST {{endpoint}}/api/cg/generate/code HTTP/1.1
content-type: application/json

{
    "module": "apicode",
    "tableName":"lc_sub_table_model",
    "fields": [
        {
            "fieldName": "template_name",
            "defaultValue":"",
            "isNotNull": 0,
            "isUnique": 0,
            "comments": "业务模板标识名称",
            "fieldType": "varchar",
            "fieldLength":26,
            "fieldFloatLength":0
        },
        {
            "fieldName": "template_label",
            "defaultValue":"",
            "isNotNull": 0,
            "isUnique": 0,
            "comments": "模板显示名称",
            "fieldType": "varchar",
            "fieldLength":26,
            "fieldFloatLength":0
        }
    ],
     "slaves":
    [
        {
            "tableName": "lc_field_item",
            "peer": 
            {
                "tableName": "lc_sub_table_model_item",
                "masterId": "sub_table_model_id",
                "masterPeerId":"field_item_id"
            }
        }
    ]
}