@endpoint = http://gitlab2.cdnline.cn:8000
# @endpoint = http://192.168.3.210:8089


### 获取所有 lowMainPage
GET {{endpoint}}/api/pageconfig/lowMainPage/lowMainPages


### 获取指定的 lowMainPages
GET {{endpoint}}/api/pageconfig/lowMainPage/lowMainPages/3


### 获取指定的 lowActionses
GET {{endpoint}}/api/pageconfig/lowActions/lowActionses/1


### 生成前端配置文件并下载
### /api/pageconfig/lowMainPage/pageConfig/{name}
POST {{endpoint}}/api/pageconfig/lowMainPage/pageConfig/configGroups
