SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `lc_low_fields`; 
CREATE TABLE `lc_low_fields` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`list_font_weight` VARCHAR(26) DEFAULT NULL COMMENT '列表字体加粗',
	`list_font_size` INT DEFAULT NULL COMMENT '列表字体大小',
	`list_font_color` VARCHAR(26) DEFAULT NULL COMMENT '列表字体颜色',
	`list_column_key` VARCHAR(26) DEFAULT NULL COMMENT '生成列表项组合',
	`list_column_name` VARCHAR(26) DEFAULT NULL COMMENT '列表项名称',
	`list_column_type` VARCHAR(26) DEFAULT NULL COMMENT '列表项组件类型',
	`list_column_layout` VARCHAR(26) DEFAULT NULL COMMENT '列表布局',
	`list_column_align` VARCHAR(26) DEFAULT NULL COMMENT '列表对齐',
	`list_column_width` SMALLINT(6) DEFAULT NULL COMMENT '列表项宽度',
	`list_column_reference` VARCHAR(26) DEFAULT NULL COMMENT '列表项指引路由',
	`list_column_format` VARCHAR(26) DEFAULT NULL COMMENT '列表项显示格式',
	`list_column_options` VARCHAR(1024) DEFAULT NULL COMMENT '组件附加属性',
	`list_column_multi_type` VARCHAR(26) DEFAULT NULL COMMENT '复合列表',
	`list_column_multi_keys` VARCHAR(1024) DEFAULT NULL COMMENT '复合列表项',
	`field_item_name` VARCHAR(26) DEFAULT NULL COMMENT '字段组件唯一名称',
	`field_binding` VARCHAR(26) DEFAULT NULL COMMENT '绑定字段名称',
	`field_label` VARCHAR(26) DEFAULT NULL COMMENT '字段名称',
	`field_value_options` VARCHAR(1024) DEFAULT NULL COMMENT '字段值下拉框选项',
	`field_value_filter` VARCHAR(1024) DEFAULT NULL COMMENT '数据转换',
	`field_scopes` VARCHAR(64) DEFAULT NULL COMMENT '字段范围',
	`field_scope` VARCHAR(26) DEFAULT NULL COMMENT '字段范围（唯一范围）',
	`form_field_title` VARCHAR(50) DEFAULT NULL COMMENT '字段表单标题',
	`form_field_hint` VARCHAR(26) DEFAULT NULL COMMENT '字段表单提示',
	`form_field_tips` VARCHAR(26) DEFAULT NULL COMMENT '字段表单输入错误提示',
	`form_input_type` VARCHAR(26) DEFAULT NULL COMMENT '表单输入组件类型',
	`form_input_options` VARCHAR(1024) DEFAULT NULL COMMENT '表单输入组件属性',
	`form_view_type` VARCHAR(26) DEFAULT NULL COMMENT '表单显示属性',
	`form_view_options` VARCHAR(1024) DEFAULT NULL COMMENT '表单输入组件属性',
	`form_input_required` SMALLINT(6) NOT NULL DEFAULT 0 COMMENT '表单是否必填',
	`form_field_question` VARCHAR(26) DEFAULT NULL COMMENT '对输入选项进行说明',
	`page_id` BIGINT(20) NOT NULL COMMENT '所属页面id',
	`list_image_width` SMALLINT(6) DEFAULT NULL COMMENT '列表图片宽度',
	`list_image_height` SMALLINT(6) DEFAULT NULL COMMENT '列表图片高度',
	`input_width` SMALLINT(6) DEFAULT NULL COMMENT '输入框宽度',
    `sort_num` varchar(20) DEFAULT '0' COMMENT '排序号',
    `field_view_one_many_options` text DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

